### ISSUE TITLE
[Issue]: Sign Up Block Putting Members in No Location Preference

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#20]
### Describe the Issue in Detail

The Sign Up block will sometimes show schedules that are full, and when those options are selected, the person gets added to the No Location Preference slot for that schedule. UPDATE: Additionally, this is happening for all teams using the Sign Up block. Even if there is only 1 location, the person is being added to No Location Preference, which is super inconvenient for our leads scheduling the teams.

### Can reproduce in

- [x] Orange App
- [X] Blue App

### Steps to Reproduce

1. Create a group with a location that is set to 1 max/desired/min for a schedule
2. Add a person to the schedule, making it full for that week
3. Use the Sign Up mobile block and select that group
4. Notice that the schedule still shows with no details of people needed; tap it
5. Notice that the person is signed up for No Location Preference

### Expected Behavior

If the schedule is full, it would only show the date info but would not allow another sign up. If a person signs up for a group with only one location at that time, it would default to that location and not No Location Preference.

### Actual Behavior

The schedule allows a new sign up when full and adds the person to the No Location Preference location. New signups are being saved under No Location Preference.

### Screenshots or Videos

![SignUpQuestions](https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/94625940/c745b92c-c3c8-48c5-a879-50cdde39452d)

### Reproduction XAML

```xml
Schedule Sign Up Template:

<StackLayout>
<StackLayout Padding="16" HorizontalOptions="Center" VerticalOptions="Center">
    <Label Text="Sign Up to Serve"
            StyleClass="text-title,font-weight-bold,text-center" 
            TextColor="#222222"  />
    <Label StyleClass="text-center"
        Text="Tap a team below to open the schedule and sign up for upcoming dates!" />
    {% if SchedulingGroupList == empty %}
        <Rock:NotificationBox NotificationType="Light" Text="You are currently not active in any groups with scheduling options. Contact your Campus Coordinator or Team Lead if you are interested in serving!" />
    {% endif %}
    
    {% for group in SchedulingGroupList %}
    <Grid> 
        <Button StyleClass="btn,btn-primary,group-selection-button" Text="{{ group.Name | Escape }}" HorizontalOptions="FillAndExpand"

            Command="{Binding ScheduleSignup.PushToSignupPage}"
            CommandParameter="{{ group.Guid }}" />
    </Grid> 
    {% endfor %} 

</StackLayout>
</StackLayout>
```

### Mobile Shell Version

v5 + v15.3

### Last Known Working Version

v5 + v14.2

### iOS Device Type(s) and iOS Version(s)

All

### Android Device Type(s) and Android Version(s)

All

**Comment by melissadrexler** [comment]
Update: I realized this is happening for all teams using the Sign Up block. Even if there is only 1 location, the person is being added to No Location Preference, which is super inconvenient for our leads scheduling the teams.

**Comment by bradencohen** [comment]
This has been fixed in v5.1 (will be app store version 1.0.70 for the blue app).

**Comment by melissadrexler** [comment]
@bradencohen Just tested our app using the Blue app, and it looks like I cannot sign up for a time that is full (which is great), but if I sign up for a time that only has one location, it still automatically puts the location as "No Location Preference".

**Comment by bradencohen** [comment]
@melissadrexler can you check in the blue app that was released today?

**Comment by melissadrexler** [comment]
@bradencohen I updated the blue app in the app store (Package 1716935419 and Shell Version 1.6.0.7), but I am still seeing the issue. Happy to do a video or screenshots if needed!
